version: '3.4'
services:
  skynetz.web:
    image: ${DOCKER_REGISTRY-}skynetz
    build:
      context: .
      dockerfile: src/Skynetz.Web/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Password#2022
      - ACCEPT_EULA=Y
    volumes:
      - ./data:/var/opt/mssql/data
    ports:
      - "1450:1433"